# Generated by Django 4.1.1 on 2025-03-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, upload_to='media/thumbnails')),
                ('userName', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Tech', 'Tech'), ('Lifestyle', 'Lifestyle'), ('business', 'business'), ('Foods', 'Foods')], default=('Tech', 'Tech'), max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'all_blogs',
            },
        ),
    ]
